---
apiVersion: v1
kind: BuildConfig
metadata:
  name: openclaw-condo
  namespace: openclaw-condo
spec:
  source:
    git:
      uri: https://github.com/navi-claw-br/openclaw-demo-kafka.git
      ref: main
    contextDir: container/
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
      - name: OPENCLAW_VERSION
        value: "latest"
  output:
    to:
      kind: ImageStreamTag
      name: openclaw-condo:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
---
apiVersion: v1
kind: ImageStream
metadata:
  name: openclaw-condo
  namespace: openclaw-condo
spec:
  lookupPolicy:
    local: true
